docker build -t udagram-api-user ./udagram-api-user
docker tag udagram-api-feed josephdaoud/udagram-api-feed:v1
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
docker push josephdaoud/udagram-api-user:v1
